/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter.api;

import java.util.concurrent.TimeUnit;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

/**
 *
 * @author BahaMoviX
 */
public class DeleteUsers extends javax.swing.JFrame {

    /**
     * Creates new form DeleteUsers
     */
    private String Email;
    private String Password;
    public DeleteUsers() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        
    }

   
    public void setData(String Email , String password)
    {
        this.Email = Email;
        this.Password = password;
        jTextPane1.setText(this.Email+"\n"+this.Password);
        
    }
    
    public void excuteDelete()
    {
        
        delay(100);
        this.deleteUsers(this.Email, this.Password);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jProgressBar1.setAutoscrolls(true);
        jProgressBar1.setOpaque(true);
        jProgressBar1.setStringPainted(true);

        jButton1.setText("الغاء");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        jButton2.setText("بدأ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
           this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         //this.jProgressBar1.setValue(50);
        this.excuteDelete();
        //jProgressBar1 = new JProgressBar();
        //jProgressBar1.setIndeterminate(true);
        
           // jProgressBar1.setValue(60);
           
          
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteUsers().setVisible(true);
            }
        });
    }
   public String mass = "";
   public WebDriver open ;
   public int sum ;
   public WebElement mainClass;
   public int index;
   public int sizeOfUsers;
    private void deleteUsers(String Email , String Password)
    {
        

        
       
     new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                open = new ChromeDriver();
        System.setProperty("webdriver.chrome.driver",System.getProperty("user.dir")+"\\chromedriver.exe");
        open.get("https://mobile.twitter.com/login");
        //open.manage().window().maximize();
        open.findElement(By.name("session[username_or_email]")).sendKeys(Email);
        open.findElement(By.name("session[password]")).sendKeys(Password);
        open.findElement(By.name("session[password]")).submit();
        open.get("https://twitter.com/following");
        sum = 1;
        mainClass = open.findElement(By.xpath("//*[@id=\"page-container\"]/div[4]/div/div/div[2]/div/div[2]/div[2]/div[2]/div[1]"));
        index = 1;
        sizeOfUsers = Integer.parseInt(open.findElement(By.xpath("//*[@id=\"page-container\"]/div[3]/div/div[2]/div[2]/div/div[2]/div/div/ul/li[1]/a/span[3]")).getText());
      // int sizeOfUsers =  Math.max(Integer.parseInt(open.findElement(By.xpath("//*[@id=\"page-container\"]/div[3]/div/div[2]/div[2]/div/div[2]/div/div/ul/li[1]/a/span[3]")).getText()), Integer.parseInt(open.findElement(By.xpath("//*[@id=\"page-container\"]/div[3]/div/div[2]/div[2]/div/div[2]/div/div/ul/li[2]/a/span[3]")).getText()));                                                              ////*[@id="page-container"]/div[3]/div/div[2]/div[2]/div/div[2]/div/div/ul/li[2]/a/span[3]
       System.out.println(sizeOfUsers);
       int xo =0;
         for(int i = 1 ; i < sizeOfUsers ; i ++)
                {
                    xo += 10;
                   jProgressBar1.setValue(xo);
                  
                    if(i%6 == 0)
                    {
                         sum++;
                         index = 1;
                         mainClass = open.findElement(By.xpath("//*[@id=\"page-container\"]/div[4]/div/div/div[2]/div/div[2]/div[2]/div[2]/div["+sum+"]"));

                    }
                    JavascriptExecutor js = (JavascriptExecutor)open;
                    js.executeScript("scrollBy(0,90)");
                    delay(150);
                     WebElement subClass = mainClass.findElement(By.xpath("//*[@id=\"page-container\"]/div[4]/div/div/div[2]/div/div[2]/div[2]/div[2]/div["+sum+"]/div["+index+"]"));
                     index++;

                    if(subClass.findElements(By.className("FollowStatus")).size() == 0)
                    {
                        System.out.println("not Follower "+subClass.findElement(By.className("fullname")).getText());
                        mass += "not Follower "+subClass.findElement(By.className("fullname")).getText()+"\n";
                         jTextPane1.setText(mass);
                        //String id = subClass.findElement(By.className("ProfileCard")).getAttribute("data-user-id");
                        //System.out.println("//*[@id=\"stream-item-user-"+id+"\"]/div/div/div[1]/div/div/div/span[2]/button[2]");
                        delay(100);
                        subClass.findElement(By.className("user-actions-follow-button")).click();
                        mass += "Succeful Deleted\n";
                        jTextPane1.setText(mass);

                        
                    }
                    else
                    {
                        System.out.println(" Follower "+subClass.findElement(By.className("fullname")).getText());
                    }
                      System.out.println("Div = "+sum+"  Element = "+index + " i = "+i);
                }
                return null;
            }
        }.execute();
       
    }
      public void delay(int n)
    {
        try {
            TimeUnit.MILLISECONDS.sleep(n);
        } catch (InterruptedException ex) {
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
